/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmstu.connection.manager.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Connection service. Represents a row in the &quot;CM_Connection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bmstu.connection.manager.core.model.impl.ConnectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bmstu.connection.manager.core.model.impl.ConnectionImpl}.
 * </p>
 *
 * @author Parhomenko
 * @see Connection
 * @see com.bmstu.connection.manager.core.model.impl.ConnectionImpl
 * @see com.bmstu.connection.manager.core.model.impl.ConnectionModelImpl
 * @generated
 */
@ProviderType
public interface ConnectionModel extends BaseModel<Connection>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a connection model instance should use the {@link Connection} interface instead.
	 */

	/**
	 * Returns the primary key of this connection.
	 *
	 * @return the primary key of this connection
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this connection.
	 *
	 * @param primaryKey the primary key of this connection
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this connection.
	 *
	 * @return the uuid of this connection
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this connection.
	 *
	 * @param uuid the uuid of this connection
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the connection ID of this connection.
	 *
	 * @return the connection ID of this connection
	 */
	public long getConnectionId();

	/**
	 * Sets the connection ID of this connection.
	 *
	 * @param connectionId the connection ID of this connection
	 */
	public void setConnectionId(long connectionId);

	/**
	 * Returns the group ID of this connection.
	 *
	 * @return the group ID of this connection
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this connection.
	 *
	 * @param groupId the group ID of this connection
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this connection.
	 *
	 * @return the company ID of this connection
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this connection.
	 *
	 * @param companyId the company ID of this connection
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this connection.
	 *
	 * @return the user ID of this connection
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this connection.
	 *
	 * @param userId the user ID of this connection
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this connection.
	 *
	 * @return the user uuid of this connection
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this connection.
	 *
	 * @param userUuid the user uuid of this connection
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this connection.
	 *
	 * @return the user name of this connection
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this connection.
	 *
	 * @param userName the user name of this connection
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this connection.
	 *
	 * @return the create date of this connection
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this connection.
	 *
	 * @param createDate the create date of this connection
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this connection.
	 *
	 * @return the modified date of this connection
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this connection.
	 *
	 * @param modifiedDate the modified date of this connection
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this connection.
	 *
	 * @return the status of this connection
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this connection.
	 *
	 * @param status the status of this connection
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this connection.
	 *
	 * @return the status by user ID of this connection
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this connection.
	 *
	 * @param statusByUserId the status by user ID of this connection
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this connection.
	 *
	 * @return the status by user uuid of this connection
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this connection.
	 *
	 * @param statusByUserUuid the status by user uuid of this connection
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this connection.
	 *
	 * @return the status by user name of this connection
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this connection.
	 *
	 * @param statusByUserName the status by user name of this connection
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this connection.
	 *
	 * @return the status date of this connection
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this connection.
	 *
	 * @param statusDate the status date of this connection
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the admin of this connection.
	 *
	 * @return the admin of this connection
	 */
	public boolean getAdmin();

	/**
	 * Returns <code>true</code> if this connection is admin.
	 *
	 * @return <code>true</code> if this connection is admin; <code>false</code> otherwise
	 */
	public boolean isAdmin();

	/**
	 * Sets whether this connection is admin.
	 *
	 * @param admin the admin of this connection
	 */
	public void setAdmin(boolean admin);

	/**
	 * Returns the name of this connection.
	 *
	 * @return the name of this connection
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this connection.
	 *
	 * @param name the name of this connection
	 */
	public void setName(String name);

	/**
	 * Returns the email of this connection.
	 *
	 * @return the email of this connection
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this connection.
	 *
	 * @param email the email of this connection
	 */
	public void setEmail(String email);

	/**
	 * Returns the password of this connection.
	 *
	 * @return the password of this connection
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this connection.
	 *
	 * @param password the password of this connection
	 */
	public void setPassword(String password);

	/**
	 * Returns the connection attributes of this connection.
	 *
	 * @return the connection attributes of this connection
	 */
	@AutoEscape
	public String getConnectionAttributes();

	/**
	 * Sets the connection attributes of this connection.
	 *
	 * @param connectionAttributes the connection attributes of this connection
	 */
	public void setConnectionAttributes(String connectionAttributes);

	/**
	 * Returns <code>true</code> if this connection is approved.
	 *
	 * @return <code>true</code> if this connection is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this connection is denied.
	 *
	 * @return <code>true</code> if this connection is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this connection is a draft.
	 *
	 * @return <code>true</code> if this connection is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this connection is expired.
	 *
	 * @return <code>true</code> if this connection is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this connection is inactive.
	 *
	 * @return <code>true</code> if this connection is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this connection is incomplete.
	 *
	 * @return <code>true</code> if this connection is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this connection is pending.
	 *
	 * @return <code>true</code> if this connection is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this connection is scheduled.
	 *
	 * @return <code>true</code> if this connection is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Connection connection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Connection> toCacheModel();

	@Override
	public Connection toEscapedModel();

	@Override
	public Connection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}